-- Enums
CREATE TYPE estado_usuario AS ENUM ('ALTA', 'BAJA');
CREATE TYPE estado_envio AS ENUM (
    'REGISTRADO', 'ELIMINADO', 'EN_TRANSITO',
    'EN_SUCURSAL', 'EN_DISTRIBUCION', 'ENTREGADO',
    'BLOQUEADO', 'RETRASADO', 'CANCELADO'
);
CREATE TYPE nivel_prioridad AS ENUM ('ALTA', 'MEDIA', 'BAJA');
CREATE TYPE accion_envio AS ENUM (
    'CREACION', 'MODIFICACION', 'CAMBIO_ESTADO', 'MOVIMIENTO', 'ELIMINACION'
);
CREATE TYPE accion_usuario AS ENUM ('ALTA', 'BAJA', 'LOGIN', 'LOGOUT');

